#!/usr/bin/env pytest

import json
import os
import subprocess
from typing import Dict, List

import pytest

HERE = os.path.dirname(os.path.realpath(__file__))

# test files and their expected codecs
TEST_FILES = [
    ("test-libaom-av1.mp4", "av1"),
    ("test-libvpx-vp9.mp4", "vp9"),
    ("test-libx264.mp4", "h264"),
    ("test-libx265.mp4", "hevc"),
    ("test-mpeg2video.ts", "mpeg2"),
    ("test-mpeg2video.mpg", "mpeg2"),
]


def run_parser(video_file: str, num_frames: int = 2) -> tuple[List[Dict], Dict, Dict]:
    """Call the video parser on the given video file and return frame info, sequence info and summary."""

    # get stdout only
    output = subprocess.check_output(
        [
            "../build/VideoParserCli/video-parser",
            video_file,
            "-n",  # number of frames to parse
            str(num_frames),
        ],
        cwd=HERE,
    )

    # parse the ldjson output
    frame_info: List[Dict] = []
    sequence_info: Dict = {}
    summary: Dict = {}

    for line in output.decode("utf-8").splitlines():
        json_line = json.loads(line)
        if json_line["type"] == "frame_info":
            frame_info.append(json_line)
        elif json_line["type"] == "sequence_info":
            sequence_info = json_line
        elif json_line["type"] == "summary":
            summary = json_line

    return frame_info, sequence_info, summary


def call_parser(video_file: str, num_frames: int = 2) -> tuple[List[Dict], Dict]:
    """Call the video parser on the given video file and return frame info and sequence info."""
    frame_info, sequence_info, _ = run_parser(video_file, num_frames)
    return frame_info, sequence_info


class TestCLI:
    @pytest.mark.parametrize("test_file,expected_codec", TEST_FILES)
    def test_parser_cli(self, test_file: str, expected_codec: str):
        # Call parser on test file
        frame_info, sequence_info = call_parser(os.path.join(HERE, test_file))

        # Basic validation of output structure
        assert len(frame_info) == 2, "Expected 2 frames of data"
        assert sequence_info, "Expected sequence info"

        # Validate sequence info
        assert sequence_info["video_codec"] == expected_codec
        assert sequence_info["video_width"] > 0
        assert sequence_info["video_height"] > 0
        assert sequence_info["video_framerate"] > 0
        assert sequence_info["video_duration"] > 0
        assert sequence_info["video_frame_count"] > 0

        # Validate frame info for both frames
        for frame in frame_info:
            # Check required fields exist and have valid values
            assert "frame_idx" in frame
            assert "pts" in frame
            assert "dts" in frame
            assert "size" in frame and frame["size"] > 0
            assert "frame_type" in frame
            assert "is_idr" in frame
            assert frame["decode_error"] is False
            assert frame["discontinuity"] is False

            # QP values should exist and be reasonable
            assert "qp_avg" in frame
            assert "qp_min" in frame
            assert "qp_max" in frame
            assert frame["qp_min"] <= frame["qp_avg"] <= frame["qp_max"]

        # First frame should be a keyframe
        assert frame_info[0]["is_idr"] is True
        assert frame_info[0]["frame_idx"] == 0

        # Second frame should have frame_idx 1
        assert frame_info[1]["frame_idx"] == 1

    @pytest.mark.parametrize(
        "test_file", ["test-libx264.mp4", "test-libx265.mp4"]
    )
    def test_parser_cli_flushes_delayed_frames(self, test_file: str):
        frame_info, sequence_info = call_parser(
            os.path.join(HERE, test_file), num_frames=-1
        )

        assert len(frame_info) == sequence_info["video_frame_count"] == 300
        assert frame_info[-1]["frame_idx"] == 299
        assert frame_info[-1]["size"] > 0

    @pytest.mark.parametrize("test_file,_", TEST_FILES)
    @pytest.mark.parametrize("num_frames", [2, -1])
    def test_parser_cli_summary(self, test_file: str, _, num_frames: int):
        frame_info, _, summary = run_parser(os.path.join(HERE, test_file), num_frames)

        assert summary["frame_count"] == len(frame_info)
        assert summary["decode_errors"] == 0
        assert summary["corrupt_packets"] == 0
        assert summary["discontinuities"] == 0

    # Two 2-second parts at 25 fps, joined with a timestamp jump (generated by
    # util/generate-damaged-test-videos.py)
    @pytest.mark.parametrize(
        "test_file", ["test-libx264-pts-jump.ts", "test-libx264-pts-backwards.ts"]
    )
    def test_parser_cli_discontinuity(self, test_file: str):
        frame_info, sequence_info, summary = run_parser(
            os.path.join(HERE, test_file), num_frames=-1
        )

        assert len(frame_info) == 100
        assert [f["frame_idx"] for f in frame_info if f["discontinuity"]] == [50]
        assert summary["discontinuities"] == 1

        # Duration and bitrate without the gap
        assert sequence_info["video_duration"] == pytest.approx(4.0)
        video_bytes = sum(f["size"] for f in frame_info)
        assert sequence_info["video_bitrate"] == pytest.approx(
            video_bytes * 8 / 1000 / 4.0
        )

    def test_parser_cli_timestamp_wrap(self):
        frame_info, sequence_info, summary = run_parser(
            os.path.join(HERE, "test-libx264-pts-wrap.ts"), num_frames=-1
        )

        assert len(frame_info) == 50
        assert sequence_info["video_duration"] == pytest.approx(2.0)
        assert summary["discontinuities"] == 0

    def test_parser_cli_decode_errors(self):
        frame_info, _, summary = run_parser(
            os.path.join(HERE, "test-libx264-bitflip.ts"), num_frames=-1
        )

        assert len(frame_info) == 50
        errors = sum(f["decode_error"] for f in frame_info)
        assert 0 < errors < 50
        assert summary["decode_errors"] == errors

    def test_parser_cli_unknown_pixel_format(self):
        # The PMT declares the H.264 stream as MPEG-2
        result = subprocess.run(
            [
                "../build/VideoParserCli/video-parser",
                os.path.join(HERE, "test-libx264-pmt-mpeg2.ts"),
            ],
            cwd=HERE,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 1
        assert result.stdout == ""
        assert "Cannot determine the video format" in result.stderr
